apiVersion: apps/v1
kind: Deployment
metadata:
  name: mygitapp
spec:
  selector:
    matchLabels:
      run: mygitapp
  replicas: 2
  template:
    metadata:
      labels:
        run: mygitapp
    spec:
      containers:
      - name: mygitapp
        image: nginx
        ports:
        - containerPort: 80


