apiVersion: v1
kind: Service
metadata:
  name: mygitapp
  labels:
    run: mygitapp
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    nodePort: 30050
  selector:
    run: mygitapp

